app_config:
  app_mode: development
  app_name: katello-scholar
  #domain: katello-scholar.org
  domain: katellolabs.org  
  url_prefix: /katello-scholar
  host: 127.0.0.1
  port: 3000
  use_ssl: false

  foreman:
    url: https://localhost/foreman
    admin_name:
    admin_password:
    oauth_key: katello-scholar
    oauth_secret: 

  katello:
    url:
    admin_name:
    admin_password:

  scholar:
    semester_dates:
      spring:
        start:
        end:

      winter:
        start:
        end:

    provisioning_start:

  proxy:
    name:
    url:
    